import * as kv from './kv_store.tsx';

export interface Contributor {
  id: string;
  name: string;
  role: 'primary_artist' | 'featured_artist' | 'producer' | 'composer' | 'lyricist' | 'remixer';
  ipi?: string; // Interested Party Information number
  isni?: string; // International Standard Name Identifier
}

export interface TrackMetadata {
  id: string;
  releaseId: string;
  title: string;
  version?: string; // e.g., "Remix", "Acoustic", "Live"
  trackNumber: number;
  discNumber: number;
  duration: number; // in seconds
  isrc?: string; // Generated by ISRC service
  isrcRequested?: boolean;
  language: string; // ISO 639-2 code (e.g., 'eng', 'yor', 'hau')
  explicit: boolean;
  genre: string;
  subgenre?: string;
  contributors: Contributor[];
  lyrics?: string;
  audioFilePath: string;
  audioFileUrl: string;
  previewStart?: number; // Preview start time in seconds
  createdAt: string;
  updatedAt: string;
}

export interface ReleaseMetadata {
  id: string;
  userId: string;
  upc?: string; // Generated by UPC service
  upcRequested?: boolean;
  title: string;
  version?: string;
  type: 'single' | 'ep' | 'album';
  artworkPath: string;
  artworkUrl: string;
  primaryArtist: string;
  featuredArtists?: string[];
  label?: string;
  releaseDate: string; // ISO 8601 date
  originalReleaseDate?: string;
  genre: string;
  subgenre?: string;
  copyrightYear: number;
  copyrightText: string; // e.g., "© 2024 Artist Name"
  publishingRights: string; // e.g., "℗ 2024 Label Name"
  language: string;
  trackIds: string[];
  status: 'draft' | 'validated' | 'submitted' | 'live' | 'rejected';
  validationErrors?: string[];
  createdAt: string;
  updatedAt: string;
}

// Supported genres and subgenres
const GENRES: Record<string, string[]> = {
  'Afrobeats': ['Afro-Pop', 'Afro-Fusion', 'Afro-House', 'Afro-Soul'],
  'Hip-Hop/Rap': ['Trap', 'Boom Bap', 'Drill', 'Alternative Hip-Hop'],
  'R&B/Soul': ['Contemporary R&B', 'Neo-Soul', 'Alternative R&B'],
  'Pop': ['Dance Pop', 'Electropop', 'Indie Pop', 'Synth-pop'],
  'Electronic': ['House', 'Techno', 'Drum & Bass', 'Dubstep', 'Amapiano'],
  'Gospel': ['Contemporary Gospel', 'Traditional Gospel', 'Gospel Choir'],
  'Highlife': ['Traditional Highlife', 'Contemporary Highlife'],
  'Juju': ['Traditional Juju', 'Modern Juju'],
  'Fuji': ['Traditional Fuji', 'Contemporary Fuji'],
  'Reggae/Dancehall': ['Roots Reggae', 'Dancehall', 'Reggae Fusion'],
  'Alternative': ['Indie', 'Experimental', 'Art Pop'],
  'Jazz': ['Contemporary Jazz', 'Jazz Fusion', 'Smooth Jazz'],
};

// Supported languages (ISO 639-2 codes)
const SUPPORTED_LANGUAGES = [
  { code: 'eng', name: 'English' },
  { code: 'yor', name: 'Yoruba' },
  { code: 'hau', name: 'Hausa' },
  { code: 'ibo', name: 'Igbo' },
  { code: 'fra', name: 'French' },
  { code: 'ara', name: 'Arabic' },
  { code: 'spa', name: 'Spanish' },
  { code: 'por', name: 'Portuguese' },
  { code: 'swa', name: 'Swahili' },
];

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

// Validate track metadata
export function validateTrackMetadata(track: Partial<TrackMetadata>): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Title validation
  if (!track.title || track.title.trim().length === 0) {
    errors.push('Track title is required');
  } else if (track.title.length > 200) {
    errors.push('Track title must be less than 200 characters');
  }

  if (!track.trackNumber || track.trackNumber < 1) {
    errors.push('Track number must be at least 1');
  }

  if (!track.discNumber || track.discNumber < 1) {
    errors.push('Disc number must be at least 1');
  }

  // Duration validation
  if (!track.duration || track.duration <= 0) {
    errors.push('Valid track duration is required');
  } else if (track.duration < 30) {
    warnings.push('Track is shorter than 30 seconds - may not be accepted by some platforms');
  } else if (track.duration > 600) {
    warnings.push('Track is longer than 10 minutes - ensure this is correct');
  }

  // Language validation
  if (!track.language) {
    errors.push('Language is required');
  } else if (!SUPPORTED_LANGUAGES.find(l => l.code === track.language)) {
    errors.push('Invalid language code');
  }

  // Genre validation
  if (!track.genre) {
    errors.push('Genre is required');
  } else if (!GENRES[track.genre]) {
    errors.push('Invalid genre');
  }

  if (track.subgenre && track.genre) {
    const validSubgenres = GENRES[track.genre] || [];
    if (!validSubgenres.includes(track.subgenre)) {
      warnings.push('Subgenre does not match selected genre');
    }
  }

  // Contributors validation
  if (!track.contributors || track.contributors.length === 0) {
    errors.push('At least one contributor is required');
  } else {
    const hasPrimaryArtist = track.contributors.some(c => c.role === 'primary_artist');
    if (!hasPrimaryArtist) {
      errors.push('At least one primary artist is required');
    }

    track.contributors.forEach((contributor, index) => {
      if (!contributor.name || contributor.name.trim().length === 0) {
        errors.push(`Contributor ${index + 1}: Name is required`);
      }
      if (!contributor.role) {
        errors.push(`Contributor ${index + 1}: Role is required`);
      }
    });
  }

  // Audio file validation
  if (!track.audioFilePath) {
    errors.push('Audio file is required');
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

// Validate release metadata
export function validateReleaseMetadata(release: Partial<ReleaseMetadata>): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Title validation
  if (!release.title || release.title.trim().length === 0) {
    errors.push('Release title is required');
  } else if (release.title.length > 200) {
    errors.push('Release title must be less than 200 characters');
  }

  // Release type validation
  if (!release.type) {
    errors.push('Release type is required');
  } else {
    const trackCount = release.trackIds?.length || 0;
    if (release.type === 'single' && trackCount > 3) {
      errors.push('Singles can have maximum 3 tracks');
    } else if (release.type === 'ep' && (trackCount < 4 || trackCount > 6)) {
      errors.push('EPs must have 4-6 tracks');
    } else if (release.type === 'album' && trackCount < 7) {
      errors.push('Albums must have at least 7 tracks');
    }
  }

  // Artwork validation
  if (!release.artworkPath) {
    errors.push('Artwork is required');
  }

  // Primary artist validation
  if (!release.primaryArtist || release.primaryArtist.trim().length === 0) {
    errors.push('Primary artist is required');
  }

  // Release date validation
  if (!release.releaseDate) {
    errors.push('Release date is required');
  } else {
    const releaseDate = new Date(release.releaseDate);
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    if (isNaN(releaseDate.getTime())) {
      errors.push('Invalid release date format');
    } else if (releaseDate < today) {
      errors.push('Release date cannot be in the past');
    } else {
      // Check minimum lead time (14 days for most platforms)
      const minLeadTime = new Date(today);
      minLeadTime.setDate(minLeadTime.getDate() + 14);
      
      if (releaseDate < minLeadTime) {
        warnings.push('Release date is less than 14 days away - some platforms may not accept this');
      }
    }
  }

  // Copyright validation
  if (!release.copyrightYear) {
    errors.push('Copyright year is required');
  } else {
    const currentYear = new Date().getFullYear();
    if (release.copyrightYear > currentYear) {
      errors.push('Copyright year cannot be in the future');
    } else if (release.copyrightYear < 1900) {
      errors.push('Copyright year must be after 1900');
    }
  }

  if (!release.copyrightText) {
    errors.push('Copyright text is required');
  }

  if (!release.publishingRights) {
    errors.push('Publishing rights text is required');
  }

  // Genre validation
  if (!release.genre) {
    errors.push('Genre is required');
  } else if (!GENRES[release.genre]) {
    errors.push('Invalid genre');
  }

  // Language validation
  if (!release.language) {
    errors.push('Language is required');
  } else if (!SUPPORTED_LANGUAGES.find(l => l.code === release.language)) {
    errors.push('Invalid language code');
  }

  // Tracks validation
  if (!release.trackIds || release.trackIds.length === 0) {
    errors.push('At least one track is required');
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

// Create track metadata
export async function createTrackMetadata(data: Omit<TrackMetadata, 'id' | 'createdAt' | 'updatedAt'>): Promise<TrackMetadata> {
  const validation = validateTrackMetadata(data);
  if (!validation.valid) {
    throw new Error(`Track validation failed: ${validation.errors.join(', ')}`);
  }

  const id = crypto.randomUUID();
  const now = new Date().toISOString();

  const track: TrackMetadata = {
    ...data,
    id,
    createdAt: now,
    updatedAt: now,
  };

  await kv.set(`track:${id}`, track);
  await kv.set(`track:release:${data.releaseId}:${id}`, true);

  return track;
}

// Create release metadata
export async function createReleaseMetadata(data: Omit<ReleaseMetadata, 'id' | 'createdAt' | 'updatedAt' | 'status'>): Promise<ReleaseMetadata> {
  const id = crypto.randomUUID();
  const now = new Date().toISOString();

  const release: ReleaseMetadata = {
    ...data,
    id,
    status: 'draft',
    createdAt: now,
    updatedAt: now,
  };

  await kv.set(`release:${id}`, release);
  await kv.set(`release:user:${data.userId}:${id}`, true);

  return release;
}

// Get track by ID
export async function getTrackById(id: string): Promise<TrackMetadata | null> {
  return await kv.get(`track:${id}`);
}

// Get release by ID
export async function getReleaseById(id: string): Promise<ReleaseMetadata | null> {
  return await kv.get(`release:${id}`);
}

// Update track metadata
export async function updateTrackMetadata(id: string, updates: Partial<TrackMetadata>): Promise<TrackMetadata | null> {
  const track = await getTrackById(id);
  if (!track) return null;

  const updatedTrack = {
    ...track,
    ...updates,
    id: track.id,
    releaseId: track.releaseId,
    updatedAt: new Date().toISOString(),
  };

  const validation = validateTrackMetadata(updatedTrack);
  if (!validation.valid) {
    throw new Error(`Track validation failed: ${validation.errors.join(', ')}`);
  }

  await kv.set(`track:${id}`, updatedTrack);
  return updatedTrack;
}

export async function deleteTrackMetadata(id: string): Promise<TrackMetadata | null> {
  const track = await getTrackById(id);
  if (!track) return null;

  const release = await getReleaseById(track.releaseId);

  await kv.del(`track:${id}`);
  await kv.del(`track:release:${track.releaseId}:${id}`);

  if (release) {
    await updateReleaseMetadata(release.id, {
      trackIds: release.trackIds.filter((trackId) => trackId !== id),
      status: 'draft',
      validationErrors: undefined,
    });
  }

  return track;
}

// Update release metadata
export async function updateReleaseMetadata(id: string, updates: Partial<ReleaseMetadata>): Promise<ReleaseMetadata | null> {
  const release = await getReleaseById(id);
  if (!release) return null;

  const updatedRelease = {
    ...release,
    ...updates,
    id: release.id,
    userId: release.userId,
    updatedAt: new Date().toISOString(),
  };

  await kv.set(`release:${id}`, updatedRelease);
  return updatedRelease;
}

// Validate and mark release as ready
export async function validateRelease(releaseId: string): Promise<{ valid: boolean; errors: string[]; warnings: string[] }> {
  const release = await getReleaseById(releaseId);
  if (!release) {
    return { valid: false, errors: ['Release not found'], warnings: [] };
  }

  const releaseValidation = validateReleaseMetadata(release);
  const allErrors = [...releaseValidation.errors];
  const allWarnings = [...releaseValidation.warnings];

  // Validate all tracks
  for (const trackId of release.trackIds) {
    const track = await getTrackById(trackId);
    if (!track) {
      allErrors.push(`Track ${trackId} not found`);
      continue;
    }

    const trackValidation = validateTrackMetadata(track);
    allErrors.push(...trackValidation.errors.map(e => `Track "${track.title}": ${e}`));
    allWarnings.push(...trackValidation.warnings.map(w => `Track "${track.title}": ${w}`));
  }

  const valid = allErrors.length === 0;

  // Update release status
  await updateReleaseMetadata(releaseId, {
    status: valid ? 'validated' : 'draft',
    validationErrors: allErrors,
  });

  return {
    valid,
    errors: allErrors,
    warnings: allWarnings,
  };
}

// Get all releases for a user
export async function getUserReleases(userId: string): Promise<ReleaseMetadata[]> {
  const releaseKeys = await kv.getEntriesByPrefix(`release:user:${userId}:`);
  const releases: ReleaseMetadata[] = [];

  for (const key of releaseKeys) {
    const releaseId = key?.key?.split(':').pop();
    if (releaseId) {
      const release = await getReleaseById(releaseId);
      if (release) {
        releases.push(release);
      }
    }
  }

  return releases.sort((a, b) => 
    new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  );
}

// Get all tracks for a release
export async function getReleaseTracks(releaseId: string): Promise<TrackMetadata[]> {
  const release = await getReleaseById(releaseId);
  if (!release) return [];

  const tracks: TrackMetadata[] = [];
  for (const trackId of release.trackIds) {
    const track = await getTrackById(trackId);
    if (track) {
      tracks.push(track);
    }
  }

  return tracks;
}

// Export genre list
export function getGenres(): Record<string, string[]> {
  return GENRES;
}

// Export language list
export function getLanguages(): Array<{ code: string; name: string }> {
  return SUPPORTED_LANGUAGES;
}
