/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vatpvfrbgeatdeypqcrv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdHB2ZnJiZ2VhdGRleXBxY3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMzI4NTksImV4cCI6MjA4MTkwODg1OX0.ui1XKtT0D3ZwAWqa9a-BB_o-BXeGvSPShwn7sNVWvSg"