/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const fallbackProjectId = "vatpvfrbgeatdeypqcrv";
const fallbackAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdHB2ZnJiZ2VhdGRleXBxY3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMzI4NTksImV4cCI6MjA4MTkwODg1OX0.ui1XKtT0D3ZwAWqa9a-BB_o-BXeGvSPShwn7sNVWvSg";

const configuredSupabaseUrl = ((import.meta as any).env?.VITE_SUPABASE_URL as string | undefined)?.trim() || '';
const configuredAnonKey = ((import.meta as any).env?.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim() || '';

function getProjectIdFromUrl(url: string) {
	try {
		const parsed = new URL(url);
		return parsed.hostname.split('.')[0] || '';
	} catch {
		return '';
	}
}

const configuredProjectId = configuredSupabaseUrl ? getProjectIdFromUrl(configuredSupabaseUrl) : '';

export const projectId = configuredProjectId || fallbackProjectId;
export const publicAnonKey = configuredAnonKey || fallbackAnonKey;